production:
  <<: *default
  database: db/production.sqlite3
default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  username: postgres
  password: 123456

development:
  <<: *default
  database: ai_status_dev

test:
  <<: *default
  database: ai_status_test

production:
  <<: *default
  database: ai_status_prod
